import React from 'react';
import {
  AbsoluteFill,
  Video,
  Img,
  Audio,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
  interpolate,
} from 'remotion';
import { FONT_DISPLAY, FONT_BODY } from '../../fonts';
import { CinematicMinimalistKaraoke } from './CinematicMinimalistKaraoke';

export const compositionConfig = {
  id: 'CinematicEssayMaster',
  durationInSeconds: 79.52,
  fps: 30,
  width: 1080,
  height: 1920,
};

// Semantic B-roll schedule generated by semantic_broll_matcher
const BROLL_SCHEDULE = [
  {
    start: 15.47,
    end: 18.47,
    media_src: 'library/workspace/w1-establishing.jpg',
    label: 'Tài sản cốt lõi: Tệp khách hàng & Dữ liệu',
    sfx: 'library/sfx/clips/keys-typing-soft.mp3',
  },
  {
    start: 25.31,
    end: 27.81,
    media_src: 'library/workspace/w2-establishing.jpg',
    label: 'Đóng gói Lời đề nghị (Irresistible Offer)',
    sfx: 'library/sfx/clips/page-flip.mp3',
  },
  {
    start: 58.25,
    end: 61.05,
    media_src: 'library/workspace/w3-establishing.png',
    label: 'Khung chiến dịch: Cash Campaign',
    sfx: 'library/sfx/clips/pencil-scribble.mp3',
  },
  {
    start: 70.67,
    end: 73.67,
    media_src: 'library/workspace/w1-establishing.jpg',
    label: 'Thực thi ngay trên tài nguyên sẵn có',
    sfx: 'library/sfx/clips/camera-shutter.mp3',
  },
];

export const CinematicEssayMaster: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const currentTime = frame / fps;

  // 1. Virtual Multi-Cam Schedule (Alternate Wide 1.0x and Punch-In 1.15x)
  let cameraZoom = 1.0;
  if (
    (currentTime >= 3.85 && currentTime < 8.95) ||
    (currentTime >= 8.95 && currentTime < 14.2) ||
    (currentTime >= 28.0 && currentTime < 35.0) ||
    (currentTime >= 40.0 && currentTime < 49.5) ||
    (currentTime >= 62.0 && currentTime < 69.5)
  ) {
    cameraZoom = 1.15;
  }

  // 2. Active B-Roll Check
  const activeBRoll = BROLL_SCHEDULE.find(
    (b) => currentTime >= b.start && currentTime <= b.end
  );

  return (
    <AbsoluteFill style={{ backgroundColor: '#0D0C0C', overflow: 'hidden', fontFamily: FONT_BODY }}>
      {/* A-ROLL: MASTER TALKING HEAD WITH VIRTUAL PUNCH-IN */}
      <AbsoluteFill style={{ overflow: 'hidden' }}>
        <div
          style={{
            width: '100%',
            height: '100%',
            transform: `scale(${cameraZoom})`,
            transformOrigin: 'center 38%',
            transition: 'transform 0.28s cubic-bezier(0.2, 0.9, 0.3, 1)',
            filter: 'contrast(1.04) brightness(1.02) saturate(1.05)',
          }}
        >
          <Video
            src={staticFile('rough_cut_master.mp4')}
            volume={1.0}
            style={{ width: '100%', height: '100%', objectFit: 'cover' }}
          />
        </div>
      </AbsoluteFill>

      {/* SEMANTIC B-ROLL CUTAWAY OVERLAYS */}
      {activeBRoll && (() => {
        const progress = (currentTime - activeBRoll.start) / (activeBRoll.end - activeBRoll.start);
        const brollZoom = interpolate(progress, [0, 1], [1.0, 1.07]);
        const opacity = interpolate(
          currentTime,
          [activeBRoll.start, activeBRoll.start + 0.2, activeBRoll.end - 0.2, activeBRoll.end],
          [0, 1, 1, 0]
        );

        return (
          <AbsoluteFill style={{ zIndex: 40, opacity }}>
            <div
              style={{
                width: '100%',
                height: '100%',
                transform: `scale(${brollZoom})`,
                filter: 'sepia(0.06) contrast(1.05) brightness(0.96)',
              }}
            >
              <Img
                src={staticFile(activeBRoll.media_src)}
                style={{ width: '100%', height: '100%', objectFit: 'cover' }}
              />
            </div>
            {/* Subtle aesthetic tag badge */}
            <div
              style={{
                position: 'absolute',
                top: 160,
                left: 60,
                padding: '10px 22px',
                background: 'rgba(15, 13, 13, 0.82)',
                backdropFilter: 'blur(16px)',
                borderRadius: 24,
                border: '1px solid rgba(245, 184, 56, 0.35)',
                boxShadow: '0 8px 30px rgba(0, 0, 0, 0.5)',
                display: 'flex',
                alignItems: 'center',
                gap: 10,
              }}
            >
              <span
                style={{
                  width: 8,
                  height: 8,
                  borderRadius: '50%',
                  backgroundColor: '#F5B838',
                  boxShadow: '0 0 10px #F5B838',
                  display: 'inline-block',
                }}
              />
              <span
                style={{
                  fontFamily: FONT_DISPLAY,
                  fontSize: 22,
                  fontWeight: 600,
                  color: '#FFFFFF',
                  letterSpacing: 1.2,
                }}
              >
                {activeBRoll.label}
              </span>
            </div>
          </AbsoluteFill>
        );
      })()}

      {/* SUBTLE CINEMATIC VIGNETTE SCRIM */}
      <AbsoluteFill
        style={{
          pointerEvents: 'none',
          zIndex: 35,
          background:
            'linear-gradient(180deg, rgba(13, 11, 10, 0.6) 0%, rgba(13, 11, 10, 0) 18%, rgba(13, 11, 10, 0) 72%, rgba(13, 11, 10, 0.85) 100%)',
        }}
      />

      {/* AUDIO PIPELINE: CINEMATIC LOFI BED DUCKED AT -22dB */}
      <Audio
        src={staticFile('library/music/clips/lofi-warm.mp3')}
        volume={0.045}
        loop
      />

      {/* FOLEY SFX TRIGGERED BY B-ROLL AND TRANSITIONS */}
      {frame === 464 && <Audio src={staticFile('library/sfx/clips/keys-typing-soft.mp3')} volume={0.35} />}
      {frame === 759 && <Audio src={staticFile('library/sfx/clips/page-flip.mp3')} volume={0.35} />}
      {frame === 1747 && <Audio src={staticFile('library/sfx/clips/pencil-scribble.mp3')} volume={0.35} />}
      {frame === 2120 && <Audio src={staticFile('library/sfx/clips/camera-shutter.mp3')} volume={0.35} />}

      {/* CINEMATIC MINIMALIST SUBTITLES (WHITE + AMBER YELLOW) */}
      <CinematicMinimalistKaraoke />
    </AbsoluteFill>
  );
};

export default CinematicEssayMaster;
